// Compiled shader for Windows, Mac, Linux

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Legacy Shaders/VertexLit" {
Properties {
    _DeathTex("Death Texture", 2D) = "black" {}
_DissolveAmount("Dissolve Amount", Range(0,1)) = 0
 _Color ("Main Color", Color) = (1.000000,1.000000,1.000000,1.000000)
 _SpecColor ("Spec Color", Color) = (1.000000,1.000000,1.000000,1.000000)
 _Emission ("Emissive Color", Color) = (0.000000,0.000000,0.000000,0.000000)
[PowerSlider(5.0)]  _Shininess ("Shininess", Range(0.010000,1.000000)) = 0.700000
 _MainTex ("Base (RGB)", 2D) = "white" { }
}
SubShader { 
 LOD 100
 Tags { "RenderType"="Opaque" }


 // Stats for Vertex shader:
 //        d3d11: 83 avg math (74..90), 2 branch
 // Stats for Fragment shader:
 //        d3d11: 2 math, 1 texture
 Pass {
  Tags { "LIGHTMODE"="Vertex" "RenderType"="Opaque" }
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 74 math, 7 temp registers, 2 branches
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "$Globals" (128 bytes) on slot 0 {
  Vector4 _Color at 32
  Vector4 _SpecColor at 48
  Vector4 _Emission at 64
  Float _Shininess at 80
  VectorInt4 unity_VertexLightParams at 96
  Vector4 _MainTex_ST at 112
}
Constant Buffer "UnityLighting" (768 bytes) on slot 1 {
  Vector4 unity_LightColor[8] at 112
  Vector4 unity_LightPosition[8] at 240
}
Constant Buffer "UnityPerDraw" (176 bytes) on slot 2 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 3 {
  Matrix4x4 unity_MatrixV at 144
  Matrix4x4 unity_MatrixInvV at 208
  Matrix4x4 unity_MatrixVP at 272
  Vector4 glstate_lightmodel_ambient at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xyz         2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyzw
// COLOR                    1   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
// SV_POSITION              0   xyzw        3      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[8], immediateIndexed
      dcl_constantbuffer CB1[23], dynamicIndexed
      dcl_constantbuffer CB2[8], immediateIndexed
      dcl_constantbuffer CB3[21], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_input v2.xy
      dcl_output o0.xyzw
      dcl_output o1.xyz
      dcl_output o2.xy
      dcl_output_siv o3.xyzw, position
      dcl_temps 7
   0: mul r0.xyz, cb2[0].yyyy, cb3[10].xyzx
   1: mad r0.xyz, cb3[9].xyzx, cb2[0].xxxx, r0.xyzx
   2: mad r0.xyz, cb3[11].xyzx, cb2[0].zzzz, r0.xyzx
   3: mad r0.xyz, cb3[12].xyzx, cb2[0].wwww, r0.xyzx
   4: mul r1.xyz, cb2[1].yyyy, cb3[10].xyzx
   5: mad r1.xyz, cb3[9].xyzx, cb2[1].xxxx, r1.xyzx
   6: mad r1.xyz, cb3[11].xyzx, cb2[1].zzzz, r1.xyzx
   7: mad r1.xyz, cb3[12].xyzx, cb2[1].wwww, r1.xyzx
   8: mul r2.xyz, cb2[2].yyyy, cb3[10].xyzx
   9: mad r2.xyz, cb3[9].xyzx, cb2[2].xxxx, r2.xyzx
  10: mad r2.xyz, cb3[11].xyzx, cb2[2].zzzz, r2.xyzx
  11: mad r2.xyz, cb3[12].xyzx, cb2[2].wwww, r2.xyzx
  12: mul r3.xyz, cb2[3].yyyy, cb3[10].xyzx
  13: mad r3.xyz, cb3[9].xyzx, cb2[3].xxxx, r3.xyzx
  14: mad r3.xyz, cb3[11].xyzx, cb2[3].zzzz, r3.xyzx
  15: mad r3.xyz, cb3[12].xyzx, cb2[3].wwww, r3.xyzx
  16: mul r4.xyz, cb2[5].xyzx, cb3[13].yyyy
  17: mad r4.xyz, cb2[4].xyzx, cb3[13].xxxx, r4.xyzx
  18: mad r4.xyz, cb2[6].xyzx, cb3[13].zzzz, r4.xyzx
  19: mad r4.xyz, cb2[7].xyzx, cb3[13].wwww, r4.xyzx
  20: mul r5.xyz, cb2[5].xyzx, cb3[14].yyyy
  21: mad r5.xyz, cb2[4].xyzx, cb3[14].xxxx, r5.xyzx
  22: mad r5.xyz, cb2[6].xyzx, cb3[14].zzzz, r5.xyzx
  23: mad r5.xyz, cb2[7].xyzx, cb3[14].wwww, r5.xyzx
  24: mul r6.xyz, cb2[5].xyzx, cb3[15].yyyy
  25: mad r6.xyz, cb2[4].xyzx, cb3[15].xxxx, r6.xyzx
  26: mad r6.xyz, cb2[6].xyzx, cb3[15].zzzz, r6.xyzx
  27: mad r6.xyz, cb2[7].xyzx, cb3[15].wwww, r6.xyzx
  28: mul r1.xyz, r1.xyzx, v0.yyyy
  29: mad r0.xyz, r0.xyzx, v0.xxxx, r1.xyzx
  30: mad r0.xyz, r2.xyzx, v0.zzzz, r0.xyzx
  31: add r0.xyz, r3.xyzx, r0.xyzx
  32: dp3 r1.x, r4.xyzx, v1.xyzx
  33: dp3 r1.y, r5.xyzx, v1.xyzx
  34: dp3 r1.z, r6.xyzx, v1.xyzx
  35: dp3 r0.w, r1.xyzx, r1.xyzx
  36: rsq r0.w, r0.w
  37: mul r1.xyz, r0.wwww, r1.xyzx
  38: dp3 r0.w, r0.xyzx, r0.xyzx
  39: rsq r0.w, r0.w
  40: mad r2.xyz, cb0[2].xyzx, cb3[0].xyzx, cb0[4].xyzx
  41: mul r1.w, cb0[5].x, l(128.000000)
  42: mov r3.xyz, r2.xyzx
  43: mov r4.xyz, l(0,0,0,0)
  44: mov r2.w, l(0)
  45: loop 
  46:   ige r3.w, r2.w, cb0[6].x
  47:   breakc_nz r3.w
  48:   dp3 r3.w, r1.xyzx, cb1[r2.w + 15].xyzx
  49:   max r3.w, r3.w, l(0.000000)
  50:   mul r5.xyz, r3.wwww, cb0[2].xyzx
  51:   mul r5.xyz, r5.xyzx, cb1[r2.w + 7].xyzx
  52:   lt r3.w, l(0.000000), r3.w
  53:   if_nz r3.w
  54:     mad r6.xyz, -r0.xyzx, r0.wwww, cb1[r2.w + 15].xyzx
  55:     dp3 r3.w, r6.xyzx, r6.xyzx
  56:     rsq r3.w, r3.w
  57:     mul r6.xyz, r3.wwww, r6.xyzx
  58:     dp3 r3.w, r1.xyzx, r6.xyzx
  59:     max r3.w, r3.w, l(0.000000)
  60:     log r3.w, r3.w
  61:     mul r3.w, r1.w, r3.w
  62:     exp r3.w, r3.w
  63:     min r3.w, r3.w, l(1.000000)
  64:     mul r3.w, r3.w, l(0.500000)
  65:     mad r4.xyz, r3.wwww, cb1[r2.w + 7].xyzx, r4.xyzx
  66:   endif 
  67:   mul r5.xyz, r5.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  68:   min r5.xyz, r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  69:   add r3.xyz, r3.xyzx, r5.xyzx
  70:   iadd r2.w, r2.w, l(1)
  71: endloop 
  72: mul_sat o1.xyz, r4.xyzx, cb0[3].xyzx
  73: mov_sat o0.xyz, r3.xyzx
  74: mov_sat o0.w, cb0[2].w
  75: mad o2.xy, v2.xyxx, cb0[7].xyxx, cb0[7].zwzz
  76: mul r0.xyzw, v0.yyyy, cb2[1].xyzw
  77: mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
  78: mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
  79: add r0.xyzw, r0.xyzw, cb2[3].xyzw
  80: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
  81: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
  82: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
  83: mad o3.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
  84: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 2 math, 1 temp registers, 1 textures
Set 2D Texture "_MainTex" to slot 0

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyz 
// COLOR                    1   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
// SV_POSITION              0   xyzw        3      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps linear v0.xyz
      dcl_input_ps linear v1.xyz
      dcl_input_ps linear v2.xy
      dcl_output o0.xyzw
      dcl_temps 1
   0: sample r0.xyzw, v2.xyxx, t0.xyzw, s0
   1: mul r0.xyz, r0.xyzx, v0.xyzx
   2: mad o0.xyz, r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), v1.xyzx
   3: mov o0.w, l(1.000000)
   4: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: POINT
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 85 math, 7 temp registers, 2 branches
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "$Globals" (128 bytes) on slot 0 {
  Vector4 _Color at 32
  Vector4 _SpecColor at 48
  Vector4 _Emission at 64
  Float _Shininess at 80
  VectorInt4 unity_VertexLightParams at 96
  Vector4 _MainTex_ST at 112
}
Constant Buffer "UnityLighting" (768 bytes) on slot 1 {
  Vector4 unity_LightColor[8] at 112
  Vector4 unity_LightPosition[8] at 240
  Vector4 unity_LightAtten[8] at 368
}
Constant Buffer "UnityPerDraw" (176 bytes) on slot 2 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 3 {
  Matrix4x4 unity_MatrixV at 144
  Matrix4x4 unity_MatrixInvV at 208
  Matrix4x4 unity_MatrixVP at 272
  Vector4 glstate_lightmodel_ambient at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xyz         2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyzw
// COLOR                    1   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
// SV_POSITION              0   xyzw        3      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[8], immediateIndexed
      dcl_constantbuffer CB1[31], dynamicIndexed
      dcl_constantbuffer CB2[8], immediateIndexed
      dcl_constantbuffer CB3[21], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_input v2.xy
      dcl_output o0.xyzw
      dcl_output o1.xyz
      dcl_output o2.xy
      dcl_output_siv o3.xyzw, position
      dcl_temps 7
   0: mul r0.xyz, cb2[0].yyyy, cb3[10].xyzx
   1: mad r0.xyz, cb3[9].xyzx, cb2[0].xxxx, r0.xyzx
   2: mad r0.xyz, cb3[11].xyzx, cb2[0].zzzz, r0.xyzx
   3: mad r0.xyz, cb3[12].xyzx, cb2[0].wwww, r0.xyzx
   4: mul r1.xyz, cb2[1].yyyy, cb3[10].xyzx
   5: mad r1.xyz, cb3[9].xyzx, cb2[1].xxxx, r1.xyzx
   6: mad r1.xyz, cb3[11].xyzx, cb2[1].zzzz, r1.xyzx
   7: mad r1.xyz, cb3[12].xyzx, cb2[1].wwww, r1.xyzx
   8: mul r2.xyz, cb2[2].yyyy, cb3[10].xyzx
   9: mad r2.xyz, cb3[9].xyzx, cb2[2].xxxx, r2.xyzx
  10: mad r2.xyz, cb3[11].xyzx, cb2[2].zzzz, r2.xyzx
  11: mad r2.xyz, cb3[12].xyzx, cb2[2].wwww, r2.xyzx
  12: mul r3.xyz, cb2[3].yyyy, cb3[10].xyzx
  13: mad r3.xyz, cb3[9].xyzx, cb2[3].xxxx, r3.xyzx
  14: mad r3.xyz, cb3[11].xyzx, cb2[3].zzzz, r3.xyzx
  15: mad r3.xyz, cb3[12].xyzx, cb2[3].wwww, r3.xyzx
  16: mul r4.xyz, cb2[5].xyzx, cb3[13].yyyy
  17: mad r4.xyz, cb2[4].xyzx, cb3[13].xxxx, r4.xyzx
  18: mad r4.xyz, cb2[6].xyzx, cb3[13].zzzz, r4.xyzx
  19: mad r4.xyz, cb2[7].xyzx, cb3[13].wwww, r4.xyzx
  20: mul r5.xyz, cb2[5].xyzx, cb3[14].yyyy
  21: mad r5.xyz, cb2[4].xyzx, cb3[14].xxxx, r5.xyzx
  22: mad r5.xyz, cb2[6].xyzx, cb3[14].zzzz, r5.xyzx
  23: mad r5.xyz, cb2[7].xyzx, cb3[14].wwww, r5.xyzx
  24: mul r6.xyz, cb2[5].xyzx, cb3[15].yyyy
  25: mad r6.xyz, cb2[4].xyzx, cb3[15].xxxx, r6.xyzx
  26: mad r6.xyz, cb2[6].xyzx, cb3[15].zzzz, r6.xyzx
  27: mad r6.xyz, cb2[7].xyzx, cb3[15].wwww, r6.xyzx
  28: mul r1.xyz, r1.xyzx, v0.yyyy
  29: mad r0.xyz, r0.xyzx, v0.xxxx, r1.xyzx
  30: mad r0.xyz, r2.xyzx, v0.zzzz, r0.xyzx
  31: add r0.xyz, r3.xyzx, r0.xyzx
  32: dp3 r1.x, r4.xyzx, v1.xyzx
  33: dp3 r1.y, r5.xyzx, v1.xyzx
  34: dp3 r1.z, r6.xyzx, v1.xyzx
  35: dp3 r0.w, r1.xyzx, r1.xyzx
  36: rsq r0.w, r0.w
  37: mul r1.xyz, r0.wwww, r1.xyzx
  38: dp3 r0.w, r0.xyzx, r0.xyzx
  39: rsq r0.w, r0.w
  40: mad r2.xyz, cb0[2].xyzx, cb3[0].xyzx, cb0[4].xyzx
  41: mul r1.w, cb0[5].x, l(128.000000)
  42: mov r3.xyz, r2.xyzx
  43: mov r4.xyz, l(0,0,0,0)
  44: mov r2.w, l(0)
  45: loop 
  46:   ige r3.w, r2.w, cb0[6].x
  47:   breakc_nz r3.w
  48:   mad r5.xyz, -r0.xyzx, cb1[r2.w + 15].wwww, cb1[r2.w + 15].xyzx
  49:   dp3 r3.w, r5.xyzx, r5.xyzx
  50:   mad r4.w, cb1[r2.w + 23].z, r3.w, l(1.000000)
  51:   div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
  52:   ne r5.w, l(0.000000), cb1[r2.w + 15].w
  53:   lt r6.x, cb1[r2.w + 23].w, r3.w
  54:   and r5.w, r5.w, r6.x
  55:   max r3.w, r3.w, l(0.000001)
  56:   rsq r3.w, r3.w
  57:   mul r5.xyz, r3.wwww, r5.xyzx
  58:   mul r3.w, r4.w, l(0.500000)
  59:   movc r3.w, r5.w, l(0), r3.w
  60:   dp3 r4.w, r1.xyzx, r5.xyzx
  61:   max r4.w, r4.w, l(0.000000)
  62:   mul r6.xyz, r4.wwww, cb0[2].xyzx
  63:   mul r6.xyz, r6.xyzx, cb1[r2.w + 7].xyzx
  64:   lt r4.w, l(0.000000), r4.w
  65:   if_nz r4.w
  66:     mad r5.xyz, -r0.xyzx, r0.wwww, r5.xyzx
  67:     dp3 r4.w, r5.xyzx, r5.xyzx
  68:     rsq r4.w, r4.w
  69:     mul r5.xyz, r4.wwww, r5.xyzx
  70:     dp3 r4.w, r1.xyzx, r5.xyzx
  71:     max r4.w, r4.w, l(0.000000)
  72:     log r4.w, r4.w
  73:     mul r4.w, r1.w, r4.w
  74:     exp r4.w, r4.w
  75:     min r4.w, r4.w, l(1.000000)
  76:     mul r4.w, r3.w, r4.w
  77:     mad r4.xyz, r4.wwww, cb1[r2.w + 7].xyzx, r4.xyzx
  78:   endif 
  79:   mul r5.xyz, r3.wwww, r6.xyzx
  80:   min r5.xyz, r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  81:   add r3.xyz, r3.xyzx, r5.xyzx
  82:   iadd r2.w, r2.w, l(1)
  83: endloop 
  84: mul_sat o1.xyz, r4.xyzx, cb0[3].xyzx
  85: mov_sat o0.xyz, r3.xyzx
  86: mov_sat o0.w, cb0[2].w
  87: mad o2.xy, v2.xyxx, cb0[7].xyxx, cb0[7].zwzz
  88: mul r0.xyzw, v0.yyyy, cb2[1].xyzw
  89: mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
  90: mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
  91: add r0.xyzw, r0.xyzw, cb2[3].xyzw
  92: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
  93: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
  94: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
  95: mad o3.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
  96: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 2 math, 1 temp registers, 1 textures
Set 2D Texture "_MainTex" to slot 0

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyz 
// COLOR                    1   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
// SV_POSITION              0   xyzw        3      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps linear v0.xyz
      dcl_input_ps linear v1.xyz
      dcl_input_ps linear v2.xy
      dcl_output o0.xyzw
      dcl_temps 1
   0: sample r0.xyzw, v2.xyxx, t0.xyzw, s0
   1: mul r0.xyz, r0.xyzx, v0.xyzx
   2: mad o0.xyz, r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), v1.xyzx
   3: mov o0.w, l(1.000000)
   4: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: SPOT
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 90 math, 7 temp registers, 2 branches
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "$Globals" (128 bytes) on slot 0 {
  Vector4 _Color at 32
  Vector4 _SpecColor at 48
  Vector4 _Emission at 64
  Float _Shininess at 80
  VectorInt4 unity_VertexLightParams at 96
  Vector4 _MainTex_ST at 112
}
Constant Buffer "UnityLighting" (768 bytes) on slot 1 {
  Vector4 unity_LightColor[8] at 112
  Vector4 unity_LightPosition[8] at 240
  Vector4 unity_LightAtten[8] at 368
  Vector4 unity_SpotDirection[8] at 496
}
Constant Buffer "UnityPerDraw" (176 bytes) on slot 2 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 3 {
  Matrix4x4 unity_MatrixV at 144
  Matrix4x4 unity_MatrixInvV at 208
  Matrix4x4 unity_MatrixVP at 272
  Vector4 glstate_lightmodel_ambient at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xyz         2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyzw
// COLOR                    1   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
// SV_POSITION              0   xyzw        3      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[8], immediateIndexed
      dcl_constantbuffer CB1[39], dynamicIndexed
      dcl_constantbuffer CB2[8], immediateIndexed
      dcl_constantbuffer CB3[21], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_input v2.xy
      dcl_output o0.xyzw
      dcl_output o1.xyz
      dcl_output o2.xy
      dcl_output_siv o3.xyzw, position
      dcl_temps 7
   0: mul r0.xyz, cb2[0].yyyy, cb3[10].xyzx
   1: mad r0.xyz, cb3[9].xyzx, cb2[0].xxxx, r0.xyzx
   2: mad r0.xyz, cb3[11].xyzx, cb2[0].zzzz, r0.xyzx
   3: mad r0.xyz, cb3[12].xyzx, cb2[0].wwww, r0.xyzx
   4: mul r1.xyz, cb2[1].yyyy, cb3[10].xyzx
   5: mad r1.xyz, cb3[9].xyzx, cb2[1].xxxx, r1.xyzx
   6: mad r1.xyz, cb3[11].xyzx, cb2[1].zzzz, r1.xyzx
   7: mad r1.xyz, cb3[12].xyzx, cb2[1].wwww, r1.xyzx
   8: mul r2.xyz, cb2[2].yyyy, cb3[10].xyzx
   9: mad r2.xyz, cb3[9].xyzx, cb2[2].xxxx, r2.xyzx
  10: mad r2.xyz, cb3[11].xyzx, cb2[2].zzzz, r2.xyzx
  11: mad r2.xyz, cb3[12].xyzx, cb2[2].wwww, r2.xyzx
  12: mul r3.xyz, cb2[3].yyyy, cb3[10].xyzx
  13: mad r3.xyz, cb3[9].xyzx, cb2[3].xxxx, r3.xyzx
  14: mad r3.xyz, cb3[11].xyzx, cb2[3].zzzz, r3.xyzx
  15: mad r3.xyz, cb3[12].xyzx, cb2[3].wwww, r3.xyzx
  16: mul r4.xyz, cb2[5].xyzx, cb3[13].yyyy
  17: mad r4.xyz, cb2[4].xyzx, cb3[13].xxxx, r4.xyzx
  18: mad r4.xyz, cb2[6].xyzx, cb3[13].zzzz, r4.xyzx
  19: mad r4.xyz, cb2[7].xyzx, cb3[13].wwww, r4.xyzx
  20: mul r5.xyz, cb2[5].xyzx, cb3[14].yyyy
  21: mad r5.xyz, cb2[4].xyzx, cb3[14].xxxx, r5.xyzx
  22: mad r5.xyz, cb2[6].xyzx, cb3[14].zzzz, r5.xyzx
  23: mad r5.xyz, cb2[7].xyzx, cb3[14].wwww, r5.xyzx
  24: mul r6.xyz, cb2[5].xyzx, cb3[15].yyyy
  25: mad r6.xyz, cb2[4].xyzx, cb3[15].xxxx, r6.xyzx
  26: mad r6.xyz, cb2[6].xyzx, cb3[15].zzzz, r6.xyzx
  27: mad r6.xyz, cb2[7].xyzx, cb3[15].wwww, r6.xyzx
  28: mul r1.xyz, r1.xyzx, v0.yyyy
  29: mad r0.xyz, r0.xyzx, v0.xxxx, r1.xyzx
  30: mad r0.xyz, r2.xyzx, v0.zzzz, r0.xyzx
  31: add r0.xyz, r3.xyzx, r0.xyzx
  32: dp3 r1.x, r4.xyzx, v1.xyzx
  33: dp3 r1.y, r5.xyzx, v1.xyzx
  34: dp3 r1.z, r6.xyzx, v1.xyzx
  35: dp3 r0.w, r1.xyzx, r1.xyzx
  36: rsq r0.w, r0.w
  37: mul r1.xyz, r0.wwww, r1.xyzx
  38: dp3 r0.w, r0.xyzx, r0.xyzx
  39: rsq r0.w, r0.w
  40: mad r2.xyz, cb0[2].xyzx, cb3[0].xyzx, cb0[4].xyzx
  41: mul r1.w, cb0[5].x, l(128.000000)
  42: mov r3.xyz, r2.xyzx
  43: mov r4.xyz, l(0,0,0,0)
  44: mov r2.w, l(0)
  45: loop 
  46:   ige r3.w, r2.w, cb0[6].x
  47:   breakc_nz r3.w
  48:   mad r5.xyz, -r0.xyzx, cb1[r2.w + 15].wwww, cb1[r2.w + 15].xyzx
  49:   dp3 r3.w, r5.xyzx, r5.xyzx
  50:   mad r4.w, cb1[r2.w + 23].z, r3.w, l(1.000000)
  51:   div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
  52:   ne r5.w, l(0.000000), cb1[r2.w + 15].w
  53:   lt r6.x, cb1[r2.w + 23].w, r3.w
  54:   and r5.w, r5.w, r6.x
  55:   movc r4.w, r5.w, l(0), r4.w
  56:   max r3.w, r3.w, l(0.000001)
  57:   rsq r3.w, r3.w
  58:   mul r5.xyz, r3.wwww, r5.xyzx
  59:   dp3 r3.w, r5.xyzx, cb1[r2.w + 31].xyzx
  60:   max r3.w, r3.w, l(0.000000)
  61:   add r3.w, r3.w, -cb1[r2.w + 23].x
  62:   mul_sat r3.w, r3.w, cb1[r2.w + 23].y
  63:   mul r3.w, r3.w, r4.w
  64:   mul r3.w, r3.w, l(0.500000)
  65:   dp3 r4.w, r1.xyzx, r5.xyzx
  66:   max r4.w, r4.w, l(0.000000)
  67:   mul r6.xyz, r4.wwww, cb0[2].xyzx
  68:   mul r6.xyz, r6.xyzx, cb1[r2.w + 7].xyzx
  69:   lt r4.w, l(0.000000), r4.w
  70:   if_nz r4.w
  71:     mad r5.xyz, -r0.xyzx, r0.wwww, r5.xyzx
  72:     dp3 r4.w, r5.xyzx, r5.xyzx
  73:     rsq r4.w, r4.w
  74:     mul r5.xyz, r4.wwww, r5.xyzx
  75:     dp3 r4.w, r1.xyzx, r5.xyzx
  76:     max r4.w, r4.w, l(0.000000)
  77:     log r4.w, r4.w
  78:     mul r4.w, r1.w, r4.w
  79:     exp r4.w, r4.w
  80:     min r4.w, r4.w, l(1.000000)
  81:     mul r4.w, r3.w, r4.w
  82:     mad r4.xyz, r4.wwww, cb1[r2.w + 7].xyzx, r4.xyzx
  83:   endif 
  84:   mul r5.xyz, r3.wwww, r6.xyzx
  85:   min r5.xyz, r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  86:   add r3.xyz, r3.xyzx, r5.xyzx
  87:   iadd r2.w, r2.w, l(1)
  88: endloop 
  89: mul_sat o1.xyz, r4.xyzx, cb0[3].xyzx
  90: mov_sat o0.xyz, r3.xyzx
  91: mov_sat o0.w, cb0[2].w
  92: mad o2.xy, v2.xyxx, cb0[7].xyxx, cb0[7].zwzz
  93: mul r0.xyzw, v0.yyyy, cb2[1].xyzw
  94: mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
  95: mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
  96: add r0.xyzw, r0.xyzw, cb2[3].xyzw
  97: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
  98: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
  99: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
 100: mad o3.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
 101: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 2 math, 1 temp registers, 1 textures
Set 2D Texture "_MainTex" to slot 0

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyz 
// COLOR                    1   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
// SV_POSITION              0   xyzw        3      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps linear v0.xyz
      dcl_input_ps linear v1.xyz
      dcl_input_ps linear v2.xy
      dcl_output o0.xyzw
      dcl_temps 1
   0: sample r0.xyzw, v2.xyxx, t0.xyzw, s0
   1: mul r0.xyz, r0.xyzx, v0.xyzx
   2: mad o0.xyz, r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), v1.xyzx
   3: mov o0.w, l(1.000000)
   4: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 11 math
 // Stats for Fragment shader:
 //        d3d11: 2 math, 2 texture
 Pass {
  Tags { "LIGHTMODE"="VertexLM" "RenderType"="Opaque" }
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 11 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "TexCoord1"
Uses vertex data channel "TexCoord0"

Constant Buffer "$Globals" (80 bytes) on slot 0 {
  Vector4 unity_Lightmap_ST at 32
  Vector4 _MainTex_ST at 48
}
Constant Buffer "UnityPerDraw" (176 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 2 {
  Matrix4x4 unity_MatrixVP at 272
}
Constant Buffer "UnityLightmaps" (32 bytes) on slot 3 {
  Vector4 unity_LightmapST at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// TEXCOORD                 1   xyz         1     NONE   float   xy  
// TEXCOORD                 0   xyz         2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// TEXCOORD                 1     zw        0     NONE   float     zw
// TEXCOORD                 2   xy          1     NONE   float   xy  
// SV_POSITION              0   xyzw        2      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[4], immediateIndexed
      dcl_constantbuffer CB2[21], immediateIndexed
      dcl_constantbuffer CB3[1], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xy
      dcl_input v2.xy
      dcl_output o0.xy
      dcl_output o0.zw
      dcl_output o1.xy
      dcl_output_siv o2.xyzw, position
      dcl_temps 2
   0: mad o0.xy, v1.xyxx, cb3[0].xyxx, cb3[0].zwzz
   1: mad o0.zw, v1.xxxy, cb0[2].xxxy, cb0[2].zzzw
   2: mad o1.xy, v2.xyxx, cb0[3].xyxx, cb0[3].zwzz
   3: mul r0.xyzw, v0.yyyy, cb1[1].xyzw
   4: mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
   5: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
   6: add r0.xyzw, r0.xyzw, cb1[3].xyzw
   7: mul r1.xyzw, r0.yyyy, cb2[18].xyzw
   8: mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
   9: mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
  10: mad o2.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
  11: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 2 math, 2 temp registers, 2 textures
Set 2D Texture "_MainTex" to slot 0 sampler slot 1
Set 2D Texture "unity_Lightmap" to slot 1 sampler slot 0

Constant Buffer "$Globals" (80 bytes) on slot 0 {
  Vector4 _Color at 64
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// TEXCOORD                 1     zw        0     NONE   float       
// TEXCOORD                 2   xy          1     NONE   float   xy  
// SV_POSITION              0   xyzw        2      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer CB0[5], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_sampler s1, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_resource_texture2d (float,float,float,float) t1
      dcl_input_ps linear v0.xy
      dcl_input_ps linear v1.xy
      dcl_output o0.xyzw
      dcl_temps 2
   0: sample r0.xyzw, v0.xyxx, t1.xyzw, s0
   1: mul r0.xyz, r0.xyzx, cb0[4].xyzx
   2: sample r1.xyzw, v1.xyxx, t0.xyzw, s1
   3: mul o0.xyz, r0.xyzx, r1.xyzx
   4: mov o0.w, l(1.000000)
   5: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 29 avg math (27..31)
 Pass {
  Name "ShadowCaster"
  Tags { "LIGHTMODE"="SHADOWCASTER" "SHADOWSUPPORT"="true" "RenderType"="Opaque" }
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: SHADOWS_DEPTH
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 31 math, 3 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"

Constant Buffer "UnityLighting" (768 bytes) on slot 0 {
  Vector4 _WorldSpaceLightPos0 at 0
}
Constant Buffer "UnityShadows" (416 bytes) on slot 1 {
  Vector4 unity_LightShadowBias at 80
}
Constant Buffer "UnityPerDraw" (176 bytes) on slot 2 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 3 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[1], immediateIndexed
      dcl_constantbuffer CB1[6], immediateIndexed
      dcl_constantbuffer CB2[7], immediateIndexed
      dcl_constantbuffer CB3[21], immediateIndexed
      dcl_input v0.xyzw
      dcl_input v1.xyz
      dcl_output_siv o0.xyzw, position
      dcl_temps 3
   0: dp3 r0.x, v1.xyzx, cb2[4].xyzx
   1: dp3 r0.y, v1.xyzx, cb2[5].xyzx
   2: dp3 r0.z, v1.xyzx, cb2[6].xyzx
   3: dp3 r0.w, r0.xyzx, r0.xyzx
   4: rsq r0.w, r0.w
   5: mul r0.xyz, r0.wwww, r0.xyzx
   6: mul r1.xyzw, v0.yyyy, cb2[1].xyzw
   7: mad r1.xyzw, cb2[0].xyzw, v0.xxxx, r1.xyzw
   8: mad r1.xyzw, cb2[2].xyzw, v0.zzzz, r1.xyzw
   9: mad r1.xyzw, cb2[3].xyzw, v0.wwww, r1.xyzw
  10: mad r2.xyz, -r1.xyzx, cb0[0].wwww, cb0[0].xyzx
  11: dp3 r0.w, r2.xyzx, r2.xyzx
  12: rsq r0.w, r0.w
  13: mul r2.xyz, r0.wwww, r2.xyzx
  14: dp3 r0.w, r0.xyzx, r2.xyzx
  15: mad r0.w, -r0.w, r0.w, l(1.000000)
  16: sqrt r0.w, r0.w
  17: mul r0.w, r0.w, cb1[5].z
  18: mad r0.xyz, -r0.xyzx, r0.wwww, r1.xyzx
  19: ne r0.w, cb1[5].z, l(0.000000)
  20: movc r0.xyz, r0.wwww, r0.xyzx, r1.xyzx
  21: mul r2.xyzw, r0.yyyy, cb3[18].xyzw
  22: mad r2.xyzw, cb3[17].xyzw, r0.xxxx, r2.xyzw
  23: mad r0.xyzw, cb3[19].xyzw, r0.zzzz, r2.xyzw
  24: mad r0.xyzw, cb3[20].xyzw, r1.wwww, r0.xyzw
  25: div r1.x, cb1[5].x, r0.w
  26: min r1.x, r1.x, l(0.000000)
  27: max r1.x, r1.x, l(-1.000000)
  28: add r0.z, r0.z, r1.x
  29: min r1.x, r0.w, r0.z
  30: mov o0.xyw, r0.xyxw
  31: add r0.x, -r0.z, r1.x
  32: mad o0.z, cb1[5].y, r0.x, r0.z
  33: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: SHADOWS_CUBE
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 27 math, 3 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"

Constant Buffer "UnityLighting" (768 bytes) on slot 0 {
  Vector4 _WorldSpaceLightPos0 at 0
}
Constant Buffer "UnityShadows" (416 bytes) on slot 1 {
  Vector4 unity_LightShadowBias at 80
}
Constant Buffer "UnityPerDraw" (176 bytes) on slot 2 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 3 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[1], immediateIndexed
      dcl_constantbuffer CB1[6], immediateIndexed
      dcl_constantbuffer CB2[7], immediateIndexed
      dcl_constantbuffer CB3[21], immediateIndexed
      dcl_input v0.xyzw
      dcl_input v1.xyz
      dcl_output_siv o0.xyzw, position
      dcl_temps 3
   0: dp3 r0.x, v1.xyzx, cb2[4].xyzx
   1: dp3 r0.y, v1.xyzx, cb2[5].xyzx
   2: dp3 r0.z, v1.xyzx, cb2[6].xyzx
   3: dp3 r0.w, r0.xyzx, r0.xyzx
   4: rsq r0.w, r0.w
   5: mul r0.xyz, r0.wwww, r0.xyzx
   6: mul r1.xyzw, v0.yyyy, cb2[1].xyzw
   7: mad r1.xyzw, cb2[0].xyzw, v0.xxxx, r1.xyzw
   8: mad r1.xyzw, cb2[2].xyzw, v0.zzzz, r1.xyzw
   9: mad r1.xyzw, cb2[3].xyzw, v0.wwww, r1.xyzw
  10: mad r2.xyz, -r1.xyzx, cb0[0].wwww, cb0[0].xyzx
  11: dp3 r0.w, r2.xyzx, r2.xyzx
  12: rsq r0.w, r0.w
  13: mul r2.xyz, r0.wwww, r2.xyzx
  14: dp3 r0.w, r0.xyzx, r2.xyzx
  15: mad r0.w, -r0.w, r0.w, l(1.000000)
  16: sqrt r0.w, r0.w
  17: mul r0.w, r0.w, cb1[5].z
  18: mad r0.xyz, -r0.xyzx, r0.wwww, r1.xyzx
  19: ne r0.w, cb1[5].z, l(0.000000)
  20: movc r0.xyz, r0.wwww, r0.xyzx, r1.xyzx
  21: mul r2.xyzw, r0.yyyy, cb3[18].xyzw
  22: mad r2.xyzw, cb3[17].xyzw, r0.xxxx, r2.xyzw
  23: mad r0.xyzw, cb3[19].xyzw, r0.zzzz, r2.xyzw
  24: mad r0.xyzw, cb3[20].xyzw, r1.wwww, r0.xyzw
  25: min r1.x, r0.w, r0.z
  26: add r1.x, -r0.z, r1.x
  27: mad o0.z, cb1[5].y, r1.x, r0.z
  28: mov o0.xyw, r0.xyxw
  29: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


 }
}
}